# Create a VPC to launch our instances into.
resource "aws_vpc" "terraform_vpc" {
  cidr_block = "${var.vpc_entire_cidr}"

  #### this 2 true values are for use the internal vpc dns resolution
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags {
    Name = "Generated by Terraform - VPC for EC2 deployment"
  }
}

# Create an internet gateway to give our vpc access to the outside world.
resource "aws_internet_gateway" "terraform_gateway" {
  vpc_id = "${aws_vpc.terraform_vpc.id}"

  tags {
    Name = "Generated by Terraform - internet gateway for VPC"
  }
}

# Create a subnet in the VPC
resource "aws_subnet" "terraform_cluster_subnet_1" {
  vpc_id            = "${aws_vpc.terraform_vpc.id}"
  cidr_block        = "10.0.1.0/24"
  availability_zone = "us-east-1a"

  tags {
    Name = "Generated by Terraform - Subnet 1"
  }
}

resource "aws_subnet" "terraform_cluster_subnet_2" {
  vpc_id            = "${aws_vpc.terraform_vpc.id}"
  cidr_block        = "10.0.2.0/24"
  availability_zone = "us-east-1b"

  tags {
    Name = "Generated by Terraform - Subnet 2"
  }
}

# Grant the VPC internet access on its main route table.
resource "aws_route_table" "terraform_route_table" {
  vpc_id = "${aws_vpc.terraform_vpc.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.terraform_gateway.id}"
  }

  tags {
    Name = "Generated by Terraform - route table for vpc access"
  }
}

resource "aws_route_table_association" "terraform_subnet_1_association" {
  subnet_id      = "${aws_subnet.terraform_cluster_subnet_1.id}"
  route_table_id = "${aws_route_table.terraform_route_table.id}"
}

resource "aws_route_table_association" "terraform_subnet_2_association" {
  subnet_id      = "${aws_subnet.terraform_cluster_subnet_2.id}"
  route_table_id = "${aws_route_table.terraform_route_table.id}"
}
